module Combinators where

-- combinators
b    = \a b c -> a (b c)
b1   = \a b c d -> a (b c d)
b2   = \a b c d e -> a (b c d e)
b3   = \a b c d -> a (b (c d))
c    = \a b c -> a c b
d    = \a b c d -> a b (c d)
d1   = \a b c d e -> a b c (d e)
d2   = \a b c d e -> a (b c) (d e)
e    = \a b c d e -> a b (c d e)
e1   = \a b c d e f g -> a (b c d) (e f g)
f    = \a b c -> c b a
g    = \a b c d -> a d (b c)
h    = \a b c -> a b c b
i    = \a -> a
j    = \a b c d -> a b (a d c)
k    = \a b -> a
l    = \a b -> a (b b)
m    = \a -> a a
m2   = \a b -> a b (a b)
o    = \a b -> b (a b)
q    = \a b c -> b (a c)
q1   = \a b c -> a (c b)
q2   = \a b c -> b (c a)
q3   = \a b c -> c (a b)
q4   = \a b c -> c (b a)
r    = \a b c -> b c a
s    = \a b c -> a c (b c)
t    = \a b -> b a
u    = \a b -> b (a a b)
v    = \a b c -> c a b
w    = \a b -> a b b
w1   = \a b -> b a a
ir   = \a b -> a b
wr   = \a b c -> a b c c
cr   = \a b c d -> a b d c
rr   = \a b c d -> a c d b
fr   = \a b c d -> a d c b
vr   = \a b c d -> a c b d
irr  = \a b c -> a b c
wrr  = \a b c d -> a b c d d
crr  = \a b c d e -> a b c e d
rrr  = \a b c d e -> a b d e c
frr  = \a b c d e -> a b e d c
vrr  = \a b c d e -> a b e c d
ki   = \a b -> b
km   = \a b -> b b
ckm  = \a b -> a a
