title = "OST List"
[OST]
[OST.A_Shape_of_Light_A_Silent_Voice_the_Movie_Original_Soundtrack]
	name = "A Shape of Light A Silent Voice the Movie Original Soundtrack"
	status = 
	score = 
	progress = 0
	songs = 61
[OST.Ace_Attorney_OST_1-6]
	name = "Ace Attorney OST (1-6)"
	status = 
	score = 
	progress = 0
	songs = 242
[OST.Ace_Attorney_Miles_Edgeworth_Investigations]
	name = "Ace Attorney: Miles Edgeworth Investigations"
	status = 
	score = 
	progress = 0
	songs = 92
[OST.Akuyaku_Reijou_nanode_Last_Boss_wo_Kattemimashita]
	name = "Akuyaku Reijou nanode Last Boss wo Kattemimashita (悪役令嬢なのでラスボスを飼ってみました)"
	status = 
	score = 
	progress = 0
	songs = 2
[OST.Arcaea Sound Collection (Memories of Memories)
	name = "Arcaea Sound Collection (Memories of Memories)
	status = 
	score = 
	progress = 0
	songs = 223
[OST.Arknights OST.
	name = "Arknights OST.
	status = 
	score = 
	progress = 0
	songs = 220
[OST.Best Whiplash O.S.T.
	name = "Best Whiplash O.S.T.
	status = 
	score = 
	progress = 12
	songs = 12
[OST.Bleach OST
	name = "Bleach OST
	status = 
	score = 
	progress = 0
	songs = 71
[OST.Burnout Paradise Remastered
	name = "Burnout Paradise Remastered
	status = 
	score = 
	progress = 13
	songs = 33
[OST.Castle Crashers
	name = "Castle Crashers
	status = 
	score = 
	progress = 0
	songs = 11
[OST.Celeste OST - Including B-Sides and Farewell
	name = "Celeste OST - Including B-Sides and Farewell
	status = 
	score = 
	progress = 0
	songs = 43
[OST.Chainsaw Man Soundtrack EP Vol.1
	name = "Chainsaw Man Soundtrack EP Vol.1
	status = 
	score = 
	progress = 0
	songs = 29
[OST.Chainsawman OP & ED
	name = "Chainsawman OP & ED
	status = 
	score = 
	progress = 0
	songs = 13
[OST.Counter:Side
	name = "Counter:Side
	status = 
	score = 
	progress = 0
	songs = 75
[OST.Cyberpunk OST
	name = "Cyberpunk OST
	status = 
	score = 
	progress = 0
	songs = 39
[OST.DMC5 OST
	name = "DMC5 OST
	status = 
	score = 
	progress = 0
	songs = 12
[OST.Destiny 1 and 2 Full OST
	name = "Destiny 1 and 2 Full OST
	status = 
	score = 
	progress = 0
	songs = 275
[OST.DEVILMAN crybaby (Original Soundtrack)
	name = "DEVILMAN crybaby (Original Soundtrack)
	status = 
	score = 
	progress = 0
	songs = 48
[OST.Doom (Original Game Soundtrack)
	name = "Doom (Original Game Soundtrack)
	status = 
	score = 
	progress = 0
	songs = 31
[OST.Dragons Dogma Dark Arisen
	name = "Dragons Dogma Dark Arisen
	status = 
	score = 
	progress = 0
	songs = 67
[OST.Final Fantasy 15 OST
	name = "Final Fantasy 15 OST
	status = 
	score = 
	progress = 0
	songs = 223
[OST.FLCL| openings, endings & OST
	name = "FLCL| openings, endings & OST
	status = 
	score = 
	progress = 0
	songs = 50
[OST.GUILTY GEAR OST
	name = "GUILTY GEAR OST
	status = 
	score = 
	progress = 0
	songs = 143
[OST.Genshin Impact OST
	name = "Genshin Impact OST
	status = 
	score = 
	progress = 0
	songs = 592
[OST.Girls' Frontline / OST
	name = "Girls' Frontline / OST
	status = 
	score = 
	progress = 0
	songs = 90
[OST.Godzilla OST (1998)
	name = "Godzilla OST (1998)
	status = 
	score = 
	progress = 0
	songs = 11
[OST.Godzilla vs. Mechagodzilla Original Soundtrack
	name = "Godzilla vs. Mechagodzilla Original Soundtrack
	status = 
	score = 
	progress = 0
	songs = 35
[OST.Gran Turismo 4 - GT Mode 1/GT Menu OST 1
	name = "Gran Turismo 4 - GT Mode 1/GT Menu OST 1
	status = 
	score = 
	progress = 1
	songs = 1
[OST.Haibane Renmei
	name = "Haibane Renmei
	status = 
	score = 
	progress = 0
	songs = 34
[OST.Halo OST 1-3, ODST, Reach and Wars - The Bungie Games
	name = "Halo OST 1-3, ODST, Reach and Wars - The Bungie Games
	status = 
	score = 
	progress = 0
	songs = 226
[OST.Higurashi no Naku Koro ni | openings, endings & OST
	name = "Higurashi no Naku Koro ni | openings, endings & OST
	status = 
	score = 
	progress = 0
	songs = 130
[OST.Houseki no Kuni OST
	name = "Houseki no Kuni OST
	status = 
	score = 
	progress = 0
	songs = 48
[OST.Jin-Roh: Wolf Brigade (Soundscapes)
	name = "Jin-Roh: Wolf Brigade (Soundscapes)
	status = 
	score = 
	progress = 0
	songs = 11
[OST.Horimiya (Openings & Endings): All Songs 2022
	name = "Horimiya (Openings & Endings): All Songs 2022
	status = 
	score = 
	progress = 0
	songs = 10
[OST.JoJo OST
	name = "JoJo OST
	status = 
	score = 
	progress = 0
	songs = 48
[OST.Lord of the Rings OST
	name = "Lord of the Rings OST
	status = 
	score = 
	progress = 0
	songs = 110
[OST.METAL GEAR RISING REVENGEANCE Vocal Tracks Selection
	name = "METAL GEAR RISING REVENGEANCE Vocal Tracks Selection
	status = 
	score = 
	progress = 0
	songs = 27
[OST.Made In Abyss OST 1-3
	name = "Made In Abyss OST 1-3
	status = 
	score = 
	progress = 0
	songs = 114
[OST.Morrowind OST
	name = "Morrowind OST
	status = 
	score = 
	progress = 0
	songs = 95
[OST.Neural Cloud OST
	name = "Neural Cloud OST
	status = 
	score = 
	progress = 0
	songs = 52
[OST.NHK ni Youkoso! (Welcome to the N.H.K.) Soundtrack
	name = "NHK ni Youkoso! (Welcome to the N.H.K.) Soundtrack
	status = 
	score = 
	progress = 0
	songs = 52
[OST.NieR OST
	name = "NieR OST
	status = 
	score = 
	progress = 0
	songs = 143
[OST.nichijou op 1 & 2 and ed 1
	name = "nichijou op 1 & 2 and ed 1
	status = 
	score = 
	progress = 0
	songs = 3
[OST.OST - W40K Mechanicus
	name = "OST - W40K Mechanicus
	status = 
	score = 
	progress = 0
	songs = 12
[OST.Okami OST (Full)
	name = "Okami OST (Full)
	status = 
	score = 
	progress = 0
	songs = 228
[OST.Ori and the Blind Forest and Will of the Wisps
	name = "Ori and the Blind Forest and Will of the Wisps
	status = 
	score = 
	progress = 0
	songs = 92
[OST.Outer Wilds - Full OST
	name = "Outer Wilds - Full OST
	status = 
	score = 
	progress = 0
	songs = 58
[OST.PERSONA5 ORIGINAL SOUNDTRACK
	name = "PERSONA5 ORIGINAL SOUNDTRACK
	status = 
	score = 
	progress = 0
	songs = 110
[OST.Pan's Labyrinth (Original Motion Picture Soundtrack)
	name = "Pan's Labyrinth (Original Motion Picture Soundtrack)
	status = 
	score = 
	progress = 0
	songs = 21
[OST.Paripi Koumei ALL OST
	name = "Paripi Koumei ALL OST
	status = 
	score = 
	progress = 0
	songs = 14
[OST.Pay day 2 soundtrack 
	name = "Pay day 2 soundtrack 
	status = 
	score = 
	progress = 0
	songs = 41
[OST.Persona 4 Golden OST
	name = "Persona 4 Golden OST
	status = 
	score = 
	progress = 0
	songs = 194
[OST.Ping Pong (Original Soundtrack)
	name = "Ping Pong (Original Soundtrack)
	status = 
	score = 
	progress = 0
	songs = 42
[OST.Plants Vs. Zombies (Original Video Game Soundtrack)
	name = "Plants Vs. Zombies (Original Video Game Soundtrack)
	status = 
	score = 
	progress = 0
	songs = 29
[OST.Plastic memories
	name = "Plastic memories
	status = 
	score = 
	progress = 0
	songs = 8
[OST.Pokemon Black & White OST
	name = "Pokemon Black & White OST
	status = 
	score = 
	progress = 0
	songs = 199
[OST.Pokemon DPPt Soundtrack
	name = "Pokemon DPPt Soundtrack
	status = 
	score = 
	progress = 0
	songs = 249
[OST.Pokémon HeartGold/SoulSilver Soundtrack!
	name = "Pokémon HeartGold/SoulSilver Soundtrack!
	status = 
	score = 
	progress = 0
	songs = 69
[OST.Serial Experiments Lain Soundtrack
	name = "Serial Experiments Lain Soundtrack
	status = 
	score = 
	progress = 0
	songs = 84
[OST.Shoujo Shuumatsu Ryoukou ( Girls Last Tour )
	name = "Shoujo Shuumatsu Ryoukou ( Girls Last Tour )
	status = 
	score = 
	progress = 0
	songs = 4
[OST.Skullgirls: The Complete Soundtrack
	name = "Skullgirls: The Complete Soundtrack
	status = 
	score = 
	progress = 0
	songs = 43
[OST.Star Wars Soundtracks
	name = "Star Wars Soundtracks
	status = 
	score = 
	progress = 0
	songs = 679
[OST.Star Wars: Visions - The Village Bride (Original Soundtrack)
	name = "Star Wars: Visions - The Village Bride (Original Soundtrack)
	status = 
	score = 
	progress = 0
	songs = 10
[OST.Sonic Frontiers Original Soundtrack Stillness & Motion
	name = "Sonic Frontiers Original Soundtrack Stillness & Motion
	status = 
	score = 
	progress = 0
	songs = 150
[OST.Sora no Woto
	name = "Sora no Woto
	status = 
	score = 
	progress = 0
	songs = 2
[OST.Space Dandy | openings, endings & OST
	name = "Space Dandy | openings, endings & OST
	status = 
	score = 
	progress = 0
	songs = 67
[OST.Summer Time Rendering
	name = "Summer Time Rendering
	status = 
	score = 
	progress = 0
	songs = 4
[OST.Super Mario Galaxy Soundtrack
	name = "Super Mario Galaxy Soundtrack
	status = 
	score = 
	progress = 0
	songs = 33
[OST.subnautica OST
	name = "subnautica OST
	status = 
	score = 
	progress = 0
	songs = 55
[OST.ULTRAKILL OST
	name = "ULTRAKILL OST
	status = 
	score = 
	progress = 0
	songs = 19?
[OST.Undertale OST
	name = "Undertale OST
	status = 
	score = 
	progress = 0
	songs = 48
[OST.Vivy -Fluorite Eye's Song-
	name = "Vivy -Fluorite Eye's Song-
	status = 
	score = 
	progress = 0
	songs = 57
[OST.Yofukashi no uta Op & Ed
	name = "Yofukashi no uta Op & Ed
	status = 
	score = 
	progress = 0
	songs = 3
[OST.Zelda: Breath of the Wild Soundtrack Playlist
	name = "Zelda: Breath of the Wild Soundtrack Playlist
	status = 
	score = 
	progress = 0
	songs = 168
[OST.結束バンド
	name = "結束バンド
	status = 
	score = 
	progress = 0
	songs = 14
