title = "OST List"
[[OST]]
	name = 'A Shape of Light "A Silent Voice the Movie" Original Soundtrack'
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 61
[[OST]]
	name = "Ace Attorney OST (1-6)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 242
[[OST]]
	name = "Ace Attorney: Miles Edgeworth Investigations"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 92
[[OST]]
	name = "Akuyaku Reijou nanode Last Boss wo Kattemimashita (悪役令嬢なのでラスボスを飼ってみました)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 2
[[OST]]
	name = "Arcaea Sound Collection (Memories of Memories)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 223
[[OST]]
	name = "Arknights OST."
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 220
[[OST]]
	name = "Best Whiplash O.S.T."
	status =  "completed"
	score =  "S"
	progress = 12
	songs = 12
[[OST]]
	name = "Bleach OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 71
[[OST]]
	name = "Burnout Paradise Remastered"
	status =  "completed"
	score =  "SS"
	progress = 33
	songs = 33
[[OST]]
	name = "Castle Crashers"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 11
[[OST]]
	name = "Celeste OST - Including B-Sides and Farewell"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 43
[[OST]]
	name = "Chainsaw Man Soundtrack EP Vol.1"
	status =  "completed"
	score =  "S"
	progress = 29
	songs = 29
[[OST]]
	name = "Chainsawman OP & ED"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 13
[[OST]]
	name = "Counter:Side"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 75
[[OST]]
	name = "Cyberpunk OST"
	status =  "listening"
	score =  "n/a"
	progress = 10
	songs = 39
[[OST]]
	name = "DMC5 OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 12
[[OST]]
	name = "Destiny 1 and 2 Full OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 275
[[OST]]
	name = "DEVILMAN crybaby (Original Soundtrack)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 48
[[OST]]
	name = "Doom (Original Game Soundtrack)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 31
[[OST]]
	name = "Dragons Dogma Dark Arisen"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 67
[[OST]]
	name = "Final Fantasy 15 OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 223
[[OST]]
	name = "FLCL| openings, endings & OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 50
[[OST]]
	name = "GUILTY GEAR OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 143
[[OST]]
	name = "Genshin Impact OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 592
[[OST]]
	name = "Girls' Frontline / OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 90
[[OST]]
	name = "Godzilla OST (1998)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 11
[[OST]]
	name = "Godzilla vs. Mechagodzilla Original Soundtrack"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 35
[[OST]]
	name = "Gran Turismo 4 - GT Mode 1/GT Menu OST 1"
	status =  "completed"
	score =  "A"
	progress = 1
	songs = 1
[[OST]]
	name = "Haibane Renmei"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 34
[[OST]]
	name = "Halo OST 1-3, ODST, Reach and Wars - The Bungie Games"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 226
[[OST]]
	name = "Higurashi no Naku Koro ni | openings, endings & OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 130
[[OST]]
	name = "Houseki no Kuni OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 48
[[OST]]
	name = "Jin-Roh: Wolf Brigade (Soundscapes)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 11
[[OST]]
	name = "Horimiya (Openings & Endings): All Songs 2022"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 10
[[OST]]
	name = "JoJo OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 48
[[OST]]
	name = "Lord of the Rings OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 110
[[OST]]
	name = "METAL GEAR RISING REVENGEANCE Vocal Tracks Selection"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 27
[[OST]]
	name = "Made In Abyss OST 1-3"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 114
[[OST]]
	name = "Morrowind OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 95
[[OST]]
	name = "Neural Cloud OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 52
[[OST]]
	name = "NHK ni Youkoso! (Welcome to the N.H.K.) Soundtrack"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 52
[[OST]]
	name = "NieR OST"
	status =  "listening"
	score =  "n/a"
	progress = 12
	songs = 143
[[OST]]
	name = "nichijou op 1 & 2 and ed 1"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 3
[[OST]]
	name = "OST - W40K Mechanicus"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 12
[[OST]]
	name = "Okami OST (Full)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 228
[[OST]]
	name = "Ori and the Blind Forest and Will of the Wisps"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 92
[[OST]]
	name = "Outer Wilds - Full OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 58
[[OST]]
	name = "PERSONA5 ORIGINAL SOUNDTRACK"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 110
[[OST]]
	name = "Pan's Labyrinth (Original Motion Picture Soundtrack)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 21
[[OST]]
	name = "Paripi Koumei ALL OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 14
[[OST]]
	name = "Pay day 2 soundtrack "
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 41
[[OST]]
	name = "Persona 4 Golden OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 194
[[OST]]
	name = "Ping Pong (Original Soundtrack)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 42
[[OST]]
	name = "Plants Vs. Zombies (Original Video Game Soundtrack)"
	status =  "listening"
	score =  "n/a"
	progress = 5
	songs = 29
[[OST]]
	name = "Plastic memories"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 8
[[OST]]
	name = "Pokemon Black & White OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 199
[[OST]]
	name = "Pokemon DPPt Soundtrack"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 249
[[OST]]
	name = "Pokémon HeartGold/SoulSilver Soundtrack!"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 69
[[OST]]
	name = "Serial Experiments Lain Soundtrack"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 84
[[OST]]
	name = "Shoujo Shuumatsu Ryoukou ( Girls Last Tour )"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 4
[[OST]]
	name = "Skullgirls: The Complete Soundtrack"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 43
[[OST]]
	name = "Star Wars Soundtracks"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 679
[[OST]]
	name = "Star Wars: Visions - The Village Bride (Original Soundtrack)"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 10
[[OST]]
	name = "Sonic Frontiers Original Soundtrack Stillness & Motion"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 150
[[OST]]
	name = "Sora no Woto"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 2
[[OST]]
	name = "Space Dandy | openings, endings & OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 67
[[OST]]
	name = "Summer Time Rendering"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 4
[[OST]]
	name = "Super Mario Galaxy Soundtrack"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 33
[[OST]]
	name = "subnautica OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 55
[[OST]]
	name = "ULTRAKILL OST"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 19
[[OST]]
	name = "Undertale OST"
	status =  "listening"
	score =  "n/a"
	progress = 6
	songs = 48
[[OST]]
	name = "Vivy -Fluorite Eye's Song-"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 57
[[OST]]
	name = "Yofukashi no uta Op & Ed"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 3
[[OST]]
	name = "Zelda: Breath of the Wild Soundtrack Playlist"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 168
[[OST]]
	name = "結束バンド"
	status =  "planning"
	score =  "n/a"
	progress = 0
	songs = 14
